"use client";

import { Metadata } from "next";
import { usePathname } from "next/navigation";
import { useEffect } from "react";

import Navbar from "@components/Navbar";
import Footer from "@components/Footer";
import "./globals.css";
import Sidebar from "@components/Sidebar";
import { Provider } from "react-redux";
import { store } from "@redux/store";

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const showNavbar =
    pathname === "/" ||
    pathname.startsWith("/challenges&Hackathons") ||
    pathname.startsWith("/about") ||
    pathname.startsWith("/contact") ||
    pathname.startsWith("/education-institutions");

  const showSidebar = pathname.startsWith("/dashboard");

  useEffect(() => {
    if (!pathname.startsWith("/dash")) {
      document.title = "Umurava platform | Build Work Experience ";
    }
  }, [pathname]);

  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`text-black/90 w-full max-w-screen-5xl mx-auto ${
          showSidebar && "flex flex-row"
        }`}
      >
        {showNavbar && <Navbar />}
        <Provider store={store}>
          {showSidebar && <Sidebar />}

          <div
            className={`flex-1 relative h-full px-3 ${
              !showSidebar && "min-h-[50vh]"
            } ${
              showSidebar && "flex flex-col h-full min-h-[100vh]"
            } max-sm:pb-[4rem]`}
          >
            {children}
          </div>
        </Provider>
        {showNavbar && <Footer />}
      </body>
    </html>
  );
}
