'use client'

import { Metadata } from 'next';
import { usePathname } from 'next/navigation';
import { useEffect } from 'react';

import Navbar from '@components/Navbar';
import Footer from '@components/Footer';
import './globals.css';

const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const showNavbar = !pathname.startsWith('/dash');

  useEffect(() => {
    if (!pathname.startsWith('/dash')) {
      document.title = 'Umurava platform | Build Work Experience ';
    }
  }, [pathname]);

  return (
    <html lang="en"> 
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          rel="stylesheet"
        />
      </head>
      <body className="text-black/90 w-full max-w-screen-5xl mx-auto">
        {showNavbar && <Navbar />}
        <div className='flex-1 h-full min-h-[50vh]'>

        {children}
        </div>
        {showNavbar && <Footer />}
      </body>
    </html>
  );
}